import { getRandomNumber } from '@game-react/game-react/util-formatters';

/* eslint-disable-next-line */
export interface HeaderProps {}
export function Header(props: HeaderProps) {
  return (
    <div className="bg-blue-500 p-5 m-3 shadow-md shadow-slate-500 rounded-full text-center">
      <div className="text-3xl mx-2">React Micro Fronted </div>
      Number is Generated by Formatters
      <sub>
        10<sup>{getRandomNumber()}</sup>
      </sub>
    </div>
  );
}

export default Header;
